version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-deps-v1-{{ checksum "requirements.txt" }}
            - pip-deps-v1-

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - save_cache:
          key: pip-deps-v1-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Run tests
          command: |
            mkdir -p test-results
            pytest -v -rP --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-deps-v1-{{ checksum "requirements.txt" }}
            - pip-deps-v1-

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - save_cache:
          key: pip-deps-v1-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Check formatting with Black
          command: black --check .

workflows:
  test_and_lint:
    jobs:
      - build-and-test
      - lint